@startuml
package "ervaringsweek1_casino" {

skinparam classAttributeIconSize 0

    interface Wallet{}
    interface Safe{}

    interface Casino{
        {abstract} playGame(moneyPaid: int): int
    }

    class ClawMachine implements Casino{

        - numberOfTries: int
        - moneyInTheBank: int
        + getMoneyInTheBank(): int
        + readyToWin(): boolean
        + readyToWinBigTime(): boolean
        + playGame(moneyPaid: int): int

    }

    class SlotMachine implements Casino{
        - currentPayout: int
        - odds: int
        - whatOddsToGive()
        +playSlots(moneyPaid : int): int
        {abstract}+ getCurrentPayout(): int

        + playGame(moneyPaid: int): int
    }

    class Lotto implements Casino{
        - number1: int
        - number2: int
        - number3: int
        - currentPayout: int
        - didYouWin: boolean
        - rollRandomNumbers()
        + getNumbers(number1: int, number2: int, number3: int, moneyPutIn: int)
        + playGame(moneyPaid: int): int
    }


    class Roulette implements Casino{
        - amountsOfTimesHouseLost: int
        - winningNumber: int
        - payout: int
        - shouldFailSafeBeUsed(numberChosen: int)
        + rollTheRoulette(moneyPutIn: int, numberChosen:int): int
        + playGame(moneyPaid: int): int
    }


}

@endumlml